FROM node:24-bullseye-slim

# Setup the base image
RUN apt-get update -y

WORKDIR /app/

# Copy files
COPY package.json /app
COPY package-lock.json /app

# Install dependencies
RUN npm ci

# Copy directories
COPY src /app/src
COPY types /app/types
COPY mcp-server.ts /app/mcp-server.ts
COPY sst-env.d.ts /app/sst-env.d.ts
COPY tsconfig.mcp-server.json /app/tsconfig.mcp-server.json

# Build
RUN npm run build:mcp

# Clean up
RUN apt-get clean \
    && rm -r /app/src \
    && npm prune --production

WORKDIR /app/

ENTRYPOINT ["node", "dist-mcp-server/mcp-server.js"]
