services:
  postgres:
    image: 'postgres:latest'
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
