/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "MyDynamoMCPSessionCache": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MyMailgun": {
      "domain": string
      "key": string
      "type": "sst.sst.Linkable"
    }
    "MyMcpService": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "MyUserPool": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "MyUserPoolClient": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
    "MyVpc": {
      "type": "sst.aws.Vpc"
    }
    "MyWeb": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}